basePath: /api/v1
definitions:
  github_com_aliiqbal208_GoKafka-Mongo-Observability-Stack_internal_models.Product:
    description: Product information
    properties:
      description:
        example: Latest Apple smartphone with A17 Pro chip
        maxLength: 500
        minLength: 3
        type: string
      imageUrl:
        example: https://example.com/image.jpg
        type: string
      name:
        example: iPhone 15 Pro
        maxLength: 250
        minLength: 3
        type: string
      photos:
        items:
          type: string
        type: array
      price:
        example: 999.99
        type: number
      quantity:
        example: 100
        type: integer
      rating:
        example: 8
        maximum: 10
        minimum: 0
        type: integer
    required:
    - description
    - name
    - price
    - quantity
    - rating
    type: object
  github_com_aliiqbal208_GoKafka-Mongo-Observability-Stack_internal_models.ProductsList:
    properties:
      hasMore:
        type: boolean
      page:
        type: integer
      products:
        items:
          $ref: '#/definitions/github_com_aliiqbal208_GoKafka-Mongo-Observability-Stack_internal_models.Product'
        type: array
      size:
        type: integer
      totalCount:
        type: integer
      totalPages:
        type: integer
    type: object
host: localhost:5007
info:
  contact: {}
  description: Products REST API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Products microservice
  version: "1.0"
paths:
  /products:
    get:
      consumes:
      - application/json
      description: Get all products with pagination
      parameters:
      - default: "1"
        description: page number
        in: query
        name: page
        type: string
      - default: "10"
        description: number of elements
        in: query
        name: size
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_aliiqbal208_GoKafka-Mongo-Observability-Stack_internal_models.ProductsList'
      summary: Get all products
      tags:
      - Products
    post:
      consumes:
      - application/json
      description: Create new single product
      parameters:
      - description: Product data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/github_com_aliiqbal208_GoKafka-Mongo-Observability-Stack_internal_models.Product'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_aliiqbal208_GoKafka-Mongo-Observability-Stack_internal_models.Product'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Create new product
      tags:
      - Products
  /products/{product_id}:
    get:
      consumes:
      - application/json
      description: Get single product by id
      parameters:
      - description: product id
        in: path
        name: product_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_aliiqbal208_GoKafka-Mongo-Observability-Stack_internal_models.Product'
      summary: Get product by id
      tags:
      - Products
    put:
      consumes:
      - application/json
      description: Update single product by id
      parameters:
      - description: product id
        in: path
        name: product_id
        required: true
        type: string
      - description: Product data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/github_com_aliiqbal208_GoKafka-Mongo-Observability-Stack_internal_models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_aliiqbal208_GoKafka-Mongo-Observability-Stack_internal_models.Product'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Update single product
      tags:
      - Products
  /products/search:
    get:
      consumes:
      - application/json
      description: Search product by name or description
      parameters:
      - description: search text
        in: query
        name: search
        type: string
      - description: page number
        in: query
        name: page
        type: string
      - description: number of elements
        in: query
        name: size
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_aliiqbal208_GoKafka-Mongo-Observability-Stack_internal_models.ProductsList'
      summary: Search product
      tags:
      - Products
swagger: "2.0"
